language: generic 
sudo: required
services: 
  -docker

before_install:
  - docker build -t ricardoflnsousa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ricardoflnsousa/react-test npm test

after_success:
  - docker build -t ricardoflnsousa/multi-client ./client
  - docker build -t ricardoflnsousa/multi-nginx ./nginx
  - docker build -t ricardoflnsousa/multi-server ./server
  - docker build -t ricardoflnsousa/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push ricardoflnsousa/multi-client
  - docker push ricardoflnsousa/multi-nginx
  - docker push ricardoflnsousa/multi-server
  - docker push ricardoflnsousa/multi-worker
