sudo: required
services: 
  -docker

before_install:
  - docker build -t bolcha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bolcha/react-test npm test

after_success:
  - docker build -t bolcha/multi-client ./client
  - docker build -t bolcha/multi-nginx ./nginx
  - docker build -t bolcha/multi-server ./server
  - docker build -t bolcha/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push bolcha/multi-client
  - docker push bolcha/multi-nginx
  - docker push bolcha/multi-server
  - docker push bolcha/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-313676853977'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY